#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include<string.h>
#include<unistd.h>
#include<sys/types.h>

#define _XOPEN_SOURCE 700


void signalTerminationHandler(int signal_number, siginfo_t * si, void * union_context){

    printf("The main.c program has caught the %d signal, sent by the process with the PID %d\n", signal_number, si->si_pid);
    printf("The number generated by the SR/ST function is %u\n\n", si->si_value.sival_int);
}

int main(int argc, char const *argv[])
{
    pid_t S1 = fork();
    if(S1 < 0){
        perror("ERROR! Could not fork S1.");
        exit(1);
    }
    else if(S1 == 0){
        //child of main (S1)
        // printf("S1: %d\n",getpid());
        struct sigaction signal_action;
        memset(&signal_action, 0, sizeof(signal_action));
        signal_action.sa_sigaction = &signalTerminationHandler;
        signal_action.sa_flags = SA_SIGINFO;
        sigaction(SIGTERM, &signal_action, NULL); //TO CHECK
        while(1);
    }
    else{
        //parent process, with S1 as child pid
        sleep(1);
        char string_S1 [10];
        sprintf(string_S1, "%d", S1);
        // itoa(S1, string_S1, 10);
        pid_t SR = fork();
        if (SR < 0){
            perror("ERROR! Could not fork SR.");
            exit(1);
        }
        else if(SR == 0){
            //child of main (SR)
            execl("SR",string_S1, NULL);
        }
        else{
            //parent process, with S1 and SR as child pids
            
            pid_t ST = fork();
            if (ST < 0){
                perror("ERROR! Could not fork ST.");
                exit(1);
            }
            else if(ST == 0){
                //child of main (ST)
                execl("ST", string_S1, NULL);
            }
            else{
                //parent process, with S1, SR and ST as child pids
                while(1);
            }
        }
    }

    return 0;
}
